platform :ios, '9.0'

target 'OK' do
  # Pods for OK
  pod 'Firebase/Core', '~> 5.11.0'
  pod 'Firebase/Messaging', '~> 5.11.0'
  pod 'GoogleAppMeasurement', '~> 5.3.0'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

end
